### PR TITLE
Vicon plotting and API changes

### PR DESCRIPTION
**Pull request by alexdewar**
The main point of this PR is to add a basic (2D) matplotlib plotter for the Vicon system.

But as I was working on it I decided that we might be better off changing the ``getObjectData()`` function to return the objects by reference rather than value. ``getPosition()`` and ``getAttitude()`` already copy the data from the object and it seems a bit unnecessary to copy everything twice. I've also stuck a mutex in ``ObjectData`` to stop data races (and this meant I had to add a copy constructor). As we're now returning a reference to the object rather than just its data I thought I'd made sense to rename all the ``ObjectData``s etc. to just ``Object``s.

### CODE REVIEW

**Comment by alexdewar** [comment]
I take what you're saying about the matplotlib interface -- I don't particularly mind if we do the plotting with an OpenCV window or something instead.

The problem with copying the ``ObjectData`` classes every time we want data though is that there could (presumably?) be a data race where the ``m_Position`` or ``m_Attitude`` arrays are being written to with incoming data while they're being copied (regardless of whether that's because we're copying the entire ``ObjectData`` object or just reading out these arrays).

I did put most of the actual plotting code in ``plot_agent.h``. The only purpose of the ``ObjectPlotter`` class is so that we can set a flag when there is incoming data and then only refresh the plot when we need to (which I think would still be useful if we were plotting in OpenCV).

What do you think?

**Comment by alexdewar** [comment]
...although I've just checked and the Vicon does seem to be giving us data at a much faster rate than we're plotting it any way. So we could just drop the ``ObjectPlotter`` class.

**Comment by neworderofjamie** [comment]
Unless I'm missing something the ``Vicon::UDP::m_ObjectDataMutex`` means that object data is either being copied (using ``Vicon::UDP::getObjectData()``) or being updated (using ``Vicon::UDP::updateObjectData()``)

**Comment by neworderofjamie** [comment]
Yeah - I think the Vicon is always going to give us data faster than we could do very much with it (especially if that is being done via python)

**Comment by alexdewar** [comment]
Ah yeah I guess so. Hmm. How about we drop everything except plot_agent.h then? I know using matplotlib probably isn't ideal but it could be useful as a stopgap. Plus it does give us scope for easily doing things like plotting trajectories etc.

**Comment by neworderofjamie** [comment]
Sure! Sorry for shitting on that somewhat :blush:

**Comment by neworderofjamie** [comment]
(Damnit github - that wasn't supposed to be a **happy** blush)

**Comment by alexdewar** [comment]
Haha nw :-p. You were def right about it

**Pull request closed without merging**
