### PR TITLE
Using LM9DS1 to stabilise unwrapping

### PR DESCRIPTION
**Pull request by neworderofjamie**
I was thinking that if we're going to use the robots on a slope, some sort of stabilisation is going to really help improve the in-silica rotation. This is my, somewhat hacky, attempt at doing it using existing code. However, **ideally** we would do the equivalent of:

1. Call ``unwrapMaps`` once with ``m_CentrePixel`` = (0, 0)
2. Copy ``m_UnwrapMapX`` and ``m_UnwrapMapY`` somewhere.
3. When we change ``m_CentrePixel``, ``cv::add`` the offset to our copy of ``m_UnwrapMapX`` and ``m_UnwrapMapY``

Rather than calling ``unwrapMaps`` every time we update the centre pixel. Do you have any thoughts on how this could be integrated with the OpenCV unwrapper?  I think the ideal API would be:
```c++
void unwrap(const cv::Mat &input, cv::Mat &output, degree_t roll, degree_t pitch)
```

### CODE REVIEW

**Comment by alexdewar** [comment]
What sort of frame rate do you get for this? I'd imagine that it'd be fairly slow be cool because of the frequent calls to ``updateMaps()``. If it works though I am all in favour of quick hacky solutions to problems 😉

I think probably the most efficient way to do this is to generate a massive lookup table with all of the likely possible combinations of pitch and roll (we should probably cache it on disk so we only need to do it once). Alex Cope did this for his camera code running on a Pi Zero and it worked quite nicely although I seem to remember that the lookup table ended up being at several hundred MB in size. A Jetson could definitely handle this though.

**Comment by alexdewar** [comment]
I think you're right that that's how the API should look btw.

I also think we should maybe change the API for the IMU to use the unit library while we're at it.

**Comment by neworderofjamie** [comment]
15ish doing nothing else on the Jetson so really not too slow. I don't really think a LUT is a sensible solution for this tbh - I would imagine that adding a scalar to an array of a few thousand floats (i.e. small enough to fit in L2 cache) is gonna be faster.

**Comment by neworderofjamie** [comment]
Is my maths right that that is all that's required?

**Comment by ajc158** [comment]
Unfortunately nope - that maths doesn't work! You need to do a whole
rotation matrix on each point then reproject onto the source image - this
is very computationally expensive but I'm working on a faster solution
using quaternions and hacks

**Comment by neworderofjamie** [comment]
Ooh hello! Have you seen our unwrapping code (https://github.com/BrainsOnBoard/bob_robotics/blob/master/imgproc/opencv_unwrap_360.h#L158)?Where I'm talking about adding the position is to the polar coordinate map that go into the ``cv::remap`` function. Isn't that the same?

Multiplying quaternions by vectors **generally** requires more operations that multiplying matrices by vectors btw...

**Comment by ajc158** [comment]
Doing this on my phone so might get it wrong, but the issue would be the
remapping to sphere section, which using sin and cos is most of the
computation and breaks the simple addition

**Comment by ajc158** [comment]
Also, yep - I'm aware of the extra ops if you don't compose a matrix - but
for simplicity sake I'm doing the simple version first as I'm likely memory
bound on the QPUs still!

**Pull request closed without merging**
